/** Auth */
export const LOGGING_USER_SUCCEEDED = 'LOGGING_USER_SUCCEEDED';
export const LOGGINGOUT_USER_SUCCEEDED = 'LOGGINGOUT_USER_SUCCEEDED';

/*** Cart ***/
export const LOADING_CART = 'LOADING_CART';
export const LOADING_CART_PRODUCTS_SUCCEEDED = 'LOADING_CART_PRODUCTS_SUCCEEDED';
export const LOADING_CART_PRODUCTS_FAILED = 'LOADING_CART_PRODUCTS_FAILED';
export const LOADING_CART_SHIPPING_ADDRESS_SUCCEEDED = 'LOADING_CART_SHIPPING_ADDRESS_SUCCEEDED';
export const UPDATING_CART_PRODUCT_SUCCEEDED = 'UPDATING_CART_PRODUCT_SUCCEEDED';
export const REMOVING_CART_PRODUCT_SUCCEEDED = 'REMOVING_CART_PRODUCT_SUCCEEDED';
export const CLEARING_CART_SUCCEEDED = 'CLEARING_CART_SUCCEEDED';

/** Chat */
export const LOADING_CHATS_SUCCEEDED = 'LOADING_CHATS_SUCCEEDED';

/** Contact */
export const LOADING_CONTACTS_SUCCEEDED = 'LOADING_CONTACTS_SUCCEEDED';
export const UPDATING_CONTACTS_SUCCEEDED = 'UPDATING_CONTACTS_SUCCEEDED';
export const REMOVING_CONTACTS_SUCCEEDED = 'REMOVING_CONTACTS_SUCCEEDED';

/** Product */
export const LISTENING_PRODUCT_SUCCEEDED = 'LISTENING_PRODUCT_SUCCEEDED';
export const LOADING_PRODUCTS_SUCCEEDED = 'LOADING_PRODUCTS_SUCCEEDED';
export const UPDATING_PRODUCTS_SUCCEEDED = 'UPDATING_PRODUCTS_SUCCEEDED';
export const REMOVING_PRODUCTS_SUCCEEDED = 'REMOVING_PRODUCTS_SUCCEEDED';



export const UI_SELECTED_IMAGE = 'UI_SELECTED_IMAGE';
export const UI_CLEAR_IMAGE = 'UI_CLEAR_IMAGE';
export const UI_REMOVE_IMAGE = 'UI_REMOVE_IMAGE';
